It throws an error, as expected.
